version: '3.7'

services:
  zabbix-server-mysql:
    build: 
      context: .
      dockerfile: Dockerfile_server # Dockerfile với Zabbix Server, MySQL và Apache
    container_name: zabbix-server
    ports:
      - "80:80"         # Zabbix Frontend
      - "10051:10051"   # Zabbix Server
      - "3306:3306"     # MySQL
    environment:
      MYSQL_ROOT_PASSWORD: root
      TZ: "Europe/London" # Thay đổi thành timezone của bạn
    volumes:
      - zabbix_server_db_data:/var/lib/mysql
    depends_on:
      - zabbix-agent-elastic
    restart: always

  zabbix-agent-elastic:
    build: 
      context: .
      dockerfile: Dockerfile_agentd # Dockerfile với Elasticsearch, Filebeat và Zabbix Agent
    container_name: zabbix-agentd
    ports:
      - "9200:9200"     # Elasticsearch
      - "5044:5044"     # Filebeat
      - "10050:10050"   # Zabbix Agent
    environment:
      TZ: "Europe/London" # Thay đổi thành timezone của bạn
    volumes:
      - elasticsearch_data:/var/lib/elasticsearch
      - filebeat_data:/usr/share/filebeat
    restart: always

volumes:
  zabbix_server_db_data:
    driver: local
  elasticsearch_data:
    driver: local
  filebeat_data:
    driver: local
