# Sử dụng hình ảnh nền của Ubuntu
FROM ubuntu:20.04

# Thiết lập biến môi trường để không bị hỏi khi cài đặt
ENV DEBIAN_FRONTEND=noninteractive

RUN mkdir /ai
WORKDIR /ai
COPY ./agent/ai /ai

# Cập nhật hệ thống và cài đặt các gói cần thiết
RUN apt-get update && \
    apt-get install -y \
    wget \
    curl \
    apt-transport-https \
    gnupg \
    nginx \
    software-properties-common && \
    add-apt-repository ppa:deadsnakes/ppa && \
    apt-get update && \
    apt-get install -y python3.10 python3.10-distutils python3.10-venv \
    python3-pip \
    libpcap0.8 \
    dos2unix \
    cron \
    nano \
    jq \
    openssh-server \
    lsb-release
    
# Cài đặt pip cho Python 3.10
RUN curl -sS https://bootstrap.pypa.io/get-pip.py | python3.10


# Thêm kho lưu trữ Elastic để cài đặt Filebeat
RUN wget -qO - https://artifacts.elastic.co/GPG-KEY-elasticsearch | apt-key add - && \
    echo "deb https://artifacts.elastic.co/packages/7.x/apt stable main" > /etc/apt/sources.list.d/elastic-7.x.list && \
    apt-get update && \
    apt-get install -y filebeat elasticsearch

RUN filebeat modules enable nginx

# Cài đặt Zabbix Agent
RUN wget https://repo.zabbix.com/zabbix/7.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_7.0-2+ubuntu20.04_all.deb && \
    dpkg -i zabbix-release_7.0-2+ubuntu20.04_all.deb && \
    apt-get update && \
    apt-get install -y zabbix-agent && \
    apt-get clean

# Sao chép tệp cấu hình Filebeat vào container
COPY ./filebeat/filebeat.yml /etc/filebeat/filebeat.yml

# Tai cac thu vien
RUN python3.10 -m pip install --upgrade pip setuptools
RUN python3.10 -m pip install -r requirements.txt

# Expose ports
EXPOSE 10050 80 9200 22

COPY ./agent/startup.sh /root/startup.sh
RUN dos2unix /root/startup.sh

# Khởi động dịch vụ
#CMD ["sh", "-c", "service nginx start && service zabbix-agent start && filebeat -e -c /etc/filebeat/filebeat.yml"]
CMD ["/bin/bash", "/root/startup.sh"]
